<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\LaborUnion.Communication\LaborUnion.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\LaborUnion.Exceptions\LaborUnion.Exceptions.csproj" />
    <ProjectReference Include="..\LaborUnion.Domain\LaborUnion.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCases\" />
    <Folder Include="Services\Configuration\" />
    <Folder Include="Services\Mapper\" />
    <Folder Include="Shared\Validators\" />
  </ItemGroup>

</Project>
